name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        # Construindo as imagens com base nas pastas de cada componente
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend ./backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend ./frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-database ./database
        
        # Fazendo o push das imagens para o Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-database

    - name: Deploy to production
      run: |
        # Simulando o deploy para produção
        echo "Imagens Docker enviadas para o Docker Hub e prontas para produção."
