name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.Senha123456 }}" | docker login -u "${{ secrets.maxwellrd }}" --password-stdin

    - name: Build and push Docker images
      run: |
        docker build -t myapp-backend ./backend
        docker build -t myapp-frontend ./frontend
        docker build -t myapp-database ./database
        docker push myapp-backend
        docker push myapp-frontend
        docker push myapp-database

    - name: Deploy to production
      run: |
        # Simulating production deployment (add real deployment commands here)
        echo "Deploying to production"
